name: .NET

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      BuildConfiguration: Release

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 2.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.1.x'
    - name: Setup .NET 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Setup .NET 5.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Build
      run: dotnet build TFeatureManagement.sln -c $BuildConfiguration
    - name: Test
      run: dotnet test -c $BuildConfiguration --no-build --verbosity normal
