name: .NET

on:
  push:
    branches: [ main, release/* ]
  pull_request:
    branches: [ main, release/*  ]
  workflow_dispatch:
    inputs:
      publish_nuget_packages:
        description: 'Publish NuGet packages'
        required: true
        type: boolean
        default: false


jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with: 
        dotnet-version: |
          6.0.x
          8.0.x

    - name: Restore dependencies
      run: |
        dotnet restore

    - name: Build
      run: |
        dotnet build --configuration Release --no-restore

    - name: Test
      run: |
        dotnet test --configuration Release --no-restore --no-build --verbosity normal
        
    - if: ${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')) && inputs.publish_nuget_packages }}
      name: Pack
      run: |
        dotnet pack "src/TFeatureManagement/TFeatureManagement.csproj" --configuration Release --no-restore --no-build
        dotnet pack "src/TFeatureManagement.AspNetCore/TFeatureManagement.AspNetCore.csproj" --configuration Release --no-restore --no-build

    - if: ${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')) && inputs.publish_nuget_packages }}
      name: Publish NuGet packages
      run: |
        dotnet nuget push "**/*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate --no-symbols
