name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true
        updateAssemblyInfo: true
        updateAssemblyInfoFilename: Directory.Build.props

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with: 
        dotnet-version: |
          8.0.x

    - name: Restore dependencies
      run: dotnet restore 'src/*.csproj'

    - name: Build
      run: dotnet build 'src/*.csproj' --no-restore

    # - name: Test
    #   run: dotnet test --no-build --verbosity normal

    - name: Pack
      #if: ${{ github.ref == 'refs/heads/main' }}
      run: dotnet pack 'src/*.csproj' --no-restore --no-build

    # - name: NuGet Push
    #   run: dotnet nuget push '*.nupkg' --skip-duplicate
