name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with: 
        dotnet-version: |
          2.1.x
          3.1.x
          5.0.x
          6.0.x
          7.0.x
          8.0.x

    # - name: Restore dependencies
    #   run: dotnet restore

    # - name: Build
    #   run: dotnet build --no-restore

    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
